(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global`*"]*)
(**)
(*(*Definicija funkcije f(t)*)*)
(*f[t_]:=Sin[t]*t^2/E*)
(**)
(*(*To\[CHacek]ka okoli katere razvijamo*)*)
(*t0=2;*)
(**)
(*(*Funkcija za izris grafa s pribli\[ZHacek]kom n-tega reda*)*)
(*IzrisGrafa[n_]:=*)
(*Plot[Evaluate[{f[t],Normal[Series[f[t],{t,t0,n}]]}],{t,0,4},*)
(*PlotLegends->{"Originalna funkcija",StringForm["Pribli\[ZHacek]ek ``. reda okoli \!\(\*SubscriptBox[\(t\), \(0\)]\)=``",n,t0]},*)
(*PlotLabel->StringForm["Pribli\[ZHacek]ki funkcije f(t) = `` okoli to\[CHacek]ke \!\(\*SubscriptBox[\(t\), \(0\)]\)=``",f[t],t0],*)
(*PlotRange->{{0,4},{-2,2}}]*)
(**)
(*(*Uporaba funkcije Manipulate za spreminjanje reda pribli\[ZHacek]ka*)*)
(*Manipulate[IzrisGrafa[n],{n,1,10,1}]*)
